name: Image Porter

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Pull Image
        run: |
          docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter:v0.18.0
          docker tag gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter:v0.18.0  ${{ secrets.DOCKERHUB_USERNAME }}/tektoncd-kubeconfigwriter:v0.18.0
          docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.18.0
          docker tag gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.18.0 ${{ secrets.DOCKERHUB_USERNAME }}/tektoncd-controller:v0.18.0

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tektoncd-kubeconfigwriter:v0.18.0
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tektoncd-controller:v0.18.0